### ISSUE TITLE
Disable Features

### ISSUE THREAD

**Issue by heywolf15** [AlttiRi/twitter-click-and-save#1]
I just want the save media feature, do I just need to put a line of code?

Edit: NVM I did it

**Comment by AlttiRi** [comment]
Currently it can be done only by editing the source code, I specially put it at the begin of the file.

For downloading you need only 3 things:
- `Features.addRequiredCSS();` for buttons positioning,
- `Features.imagesHandler();` for image downloading,
- `Features.videoHandler();` for video downloading.

```js
function execFeaturesOnce() {
    Features.addRequiredCSS();
    // Features.hideSignUpBottomBarAndMessages(doNotPlayVideosAutomatically);
    // Features.hideTrends();
    // Features.highlightVisitedLinks();
    // Features.hideTopicsToFollowInstantly();
}
function execFeaturesImmediately() {
    // Features.expandSpoilers();
}
function execFeatures() {
    Features.imagesHandler();
    Features.videoHandler();
    // Features.expandSpoilers();
    // Features.hideSignUpSection();
    // Features.hideTopicsToFollow();
    // Features.directLinks();
    // Features.handleTitle();
}
```

But this change will stay only before the next update.

Well, I need to add the popup with the settings sometime. But it's in my backlog currently.

**Comment by heywolf15** [comment]
Thank you
But this is what I did, I don't know if it breaks anything
I only know it works just based it on the looks

`function execFeaturesOnce() {
    Features.addRequiredCSS();
    Features.hideSignUpBottomBarAndMessages = false;
    Features.hideTrends = false;
    Features.highlightVisitedLinks();
    Features.hideTopicsToFollowInstantly = false;
}
function execFeaturesImmediately() {
    Features.expandSpoilers();
}
function execFeatures() {
    Features.imagesHandler();
    Features.videoHandler();
    Features.expandSpoilers();
    Features.hideSignUpSection = false;
    Features.hideTopicsToFollow = false;
    Features.directLinks = false;
    Features.handleTitle();
}`

**Comment by AlttiRi** [comment]
Well, it also will work. You just overwrite the function in `execFeatures*` hooks instead of calling it.

---

Okay, maybe today I will complite the setting popup in the beta version on [GitHub](https://github.com/AlttiRi/twitter-click-and-save/blob/master/twitter-click-and-save.user.js).
![image](https://user-images.githubusercontent.com/16310547/154853591-e509d51e-5b8f-4d90-bb36-db70c24c68fb.png)

**Comment by heywolf15** [comment]
Looks great
I'm using other scripts that have the same features, that's why I want to disable it
Thanks

**Comment by AlttiRi** [comment]
Released on GF: https://greasyfork.org/en/scripts/430132-twitter-click-n-save/diff?v1=1020861&v2=1015680
