### ISSUE TITLE
Deleted tweet - Strange saving behavior

### ISSUE THREAD

**Issue by cglmrfreeman** [AlttiRi/twitter-click-and-save#10]
If a deleted tweet remains on the timeline with multiple images, it appears the first image in the tweet can be saved as normal with the correct filename. The second image gives the "Download error" button when trying to download.

**Comment by AlttiRi** [comment]
Maybe the first image was with a little dimension?

I noted this behaviour here https://github.com/AlttiRi/twitter-click-and-save/issues/9#issuecomment-1241105967

When `?format=jpg&name=small` === `?format=jpg&name=orig`.

**Comment by AlttiRi** [comment]
Should be fixed in the last GitHub version.
https://github.com/AlttiRi/twitter-click-and-save/commit/07405d813d329f0852a2e647ad6fc336703ce28a

- Downloads the samples only if the originals are not available.
- Samples has `[sample]` mark in the filename.
- Samples are not added in the history.
