### ISSUE TITLE
[Question] Export already saved tweet database to another browser?

### ISSUE THREAD

**Issue by cglmrfreeman** [AlttiRi/twitter-click-and-save#17]
I'm upgrading my hard disk and doing a fresh distro install. I'd like to be able to transfer which tweets have already been saved to my new Firefox install but I'm not really sure where the tampermonkey data is stored for tcas.

Is it a straightforward process and my google-fu is just failing me?

**Comment by AlttiRi** [comment]
I currently did not implemented this https://github.com/AlttiRi/twitter-click-and-save/issues/12

It stores the data in LocalStorage.
You can manually copy it from the old browser to the new one.
See "ujs-..." values.

OK, I will write the temporal script to simplify the manual work.

**Comment by AlttiRi** [comment]
To export:

```js
let exportObject = [
    "ujs-click-n-save-settings",
    "ujs-images-history-by",
    "ujs-twitter-downloaded-images-names",
    "ujs-twitter-downloaded-image-tweet-ids", 
    "ujs-twitter-downloaded-video-tweet-ids"
    ].reduce((acc, name) => {
        const value = localStorage.getItem(name);
        if (value === null) {
            return acc;
        }
        acc[name] = localStorage.getItem(name);
        return acc;
    }, {});
downloadBlob(new Blob([JSON.stringify(exportObject)]), "ujs-c'n's-export.json");
function downloadBlob(blob, name, url) {
    const anchor = document.createElement("a");
    anchor.setAttribute("download", name || "");
    const blobUrl = URL.createObjectURL(blob);
    anchor.href = blobUrl + (url ? ("#" + url) : "");
    anchor.click();
    setTimeout(() => URL.revokeObjectURL(blobUrl), 30000);
}

```

To import
```js
// Soon
```

**Comment by cglmrfreeman** [comment]
OH whoops, didn't see the issue was already open, LOL! Closing as duplicate!
