### ISSUE TITLE
does this download the orig image?

### ISSUE THREAD

**Issue by silverhikari** [AlttiRi/twitter-click-and-save#20]
i have noticed that twitter has a tendency to reside images even if you go to the direct image link, where to get the original sized image you have to add "orig" . i was wonder if this userscript downloads the altered size version or the original version?

**Comment by AlttiRi** [comment]
Yeah, it does download the `orig` images, if it fails then it tries to download `4096x4096` (in 99.9 % of cases they are the same).

**Comment by silverhikari** [comment]
thank you that answers my question
