### ISSUE TITLE
Dates conflict if timezone changing extension is used

### ISSUE THREAD

**Issue by cglmrfreeman** [AlttiRi/twitter-click-and-save#21]
This is probably a non-issue, but I just realized I had a [time zone changing](https://mybrowseraddon.com/change-timezone.html) extension enabled in Firefox and it's been changing some of the dates of the twitter images downloaded with this extension. With the time zone extension disabled, some of the dates are now list the day prior when trying to download them.

Just trying to be consistent with my filenames so I don't accidentally download duplicates, though I'm sure that's bound to happen sometimes.

**Comment by AlttiRi** [comment]
I uses **UTC date** in filename.
Independently of your time zone the filename will be always the same for any people on the whole planet.
Of course, some files that was posted on the site minutes ago can have the next date value if you timezone is with `+` (+1, +2, +3...), and the previous day if your time zone is with `-`(-1, -2, -3...).

**Comment by cglmrfreeman** [comment]
See that's what I thought, but that's not what's happening...

[This post for example](https://twitter.com/Previeww0/status/1608952263237861378) gives me a filename of `[twitter] Previeww0—2022.12.30—1608952263237861378—FlQlGybXoAQ9sCm.jpg` without the extension and with the extension configured to "Etc/Greenwich", it gives this filename `[twitter] Previeww0—2022.12.31—1608952263237861378—FlQlGybXoAQ9sCm.jpg`, so it _should_ be the same regardless of what the "Change Timezone" extension does, but it isn't.

[Link to extension which has both a Firefox and Chrome version](https://mybrowseraddon.com/change-timezone.html).

**Comment by AlttiRi** [comment]
I can't reproduce this in Firefox. I tried to set +11, -11 time zones in Windows settings. 
With, or without the extension I always get the same result.


As a workaround you can edit the userscript by adding the required hours offset in ms . `-6 * 60 * 60 * 1000` for example.
```js
    function dateToDayDateString(dateValue, utc = true) {
        // console.log("dateToDayDateString", dateValue);
        const _date = new Date(+new Date(dateValue) + 24 * 60 * 60 * 1000);
```

https://github.com/AlttiRi/twitter-click-and-save/blob/7da19f74fc783f83e339b44b688b134d67134433/twitter-click-and-save.user.js#L1495-L1496

Here `dateValue` value I get from the HTTP header. It always is `Fri, 30 Dec 2022 22:20:48 GMT` (for the first image). 
I do not add any offset manually. I only use this value in the `Date` constructor and use `getUTCDate`, `getUTCMonth`, `getUTCFullYear` methods.

**Comment by AlttiRi** [comment]
Well, they did not Proxy `*UTC*` methods.

![image](https://user-images.githubusercontent.com/16310547/210169029-4a922cd6-0a46-49b8-a94f-2c699d0190d2.png)

**Comment by AlttiRi** [comment]
However, anyway for me it forks fine even with this extension in any system time zone.
Maybe you just use an old version of the extension, which incorrectly proxies *UTC* methods of the `Date` object?

**Comment by cglmrfreeman** [comment]
Interesting that it can't be reproduced, huh. I've uninstalled the extension as I don't need it anymore and it keeps activating itself somehow.
