### ISSUE TITLE
Change download path

### ISSUE THREAD

**Issue by DarkNaaz** [AlttiRi/twitter-click-and-save#22]
Is it possible that i can choose a path to save the file or it shows a dialog to ask me where to save it?
i tried changing the code but it wouldn't work

Thank you

Edit: I found a fix in browser settings

**Comment by AlttiRi** [comment]
Yeah, the simple way is to enable/disable it for all downloads in the browser's settings.

---

_There is also [`showSaveFilePicker`](https://developer.mozilla.org/en-US/docs/Web/API/Window/showSaveFilePicker), however, it is still an experimental API._

_IMHO, it's much convenient and effective to download images just with a click, and only then move all required files from the download folder to where you need, than always doing additional clicks in the file save dialogue._
