### ISSUE TITLE
Live tweet has original resolution missing

### ISSUE THREAD

**Issue by biggestsonicfan** [AlttiRi/twitter-click-and-save#23]
Greetings, I feel like there might be a better way to handle this [edge case](https://twitter.com/minaseairi_cos/status/1636661719417364482).

The tweet is live, and opening the image takes you to the `large` or `900x900` version of the image. While the white background button with caution sign correctly indicates there was an issue, I believe there should be a better way of differentiating between "this tweet was probably deleted" and "original image couldn't be grabbed but the tweet is still live so you might wanna try again later".

It might just be a site issue as Twitter can't even generate the media thumbnail for the media preview second on the user page:
![Screenshot_20230317_161805](https://user-images.githubusercontent.com/9744201/226068409-265d7565-9b6a-4a94-b7eb-08799257c4e1.png)

**Comment by AlttiRi** [comment]
The tweet is alive, but the `orig`, or `4096x4096` image is not available:
https://pbs.twimg.com/media/FraXJ1caAAA8a7I?format=jpg&name=orig
https://pbs.twimg.com/media/FraXJ1caAAA8a7I?format=jpg&name=4096x4096
So, it correctly indicates the issue.

Even if it will try to open the image, Twitter's UI shows the warning too:
![image](https://user-images.githubusercontent.com/16310547/226090618-1daea989-5aa5-49cc-af30-a0cd575c8cd8.png)

**Comment by AlttiRi** [comment]
BTW, yes, seems it's a temporal issue.
I have checked the my `[twitter][sample]` images, they are downloaded fine now.

**Comment by AlttiRi** [comment]
To check is the tweet is deleted... well, technically, it's possible. 
Maybe just to try to `fetch` the tweet's page and check the `status` code (is it `404`).

Although, this is very rare case to face it.
