### ISSUE TITLE
If twitter shortened URLs are used as URLs, http(s) is stuck in front of them

### ISSUE THREAD

**Issue by cglmrfreeman** [AlttiRi/twitter-click-and-save#3]
Example taken from [@ehrrr_](https://twitter.com/ehrrr_)'s profile. You have to be crazy to do this, but apparently some people _do_ do this.

**Comment by AlttiRi** [comment]
Interesting:
![image](https://user-images.githubusercontent.com/16310547/170221898-45d04cc6-bab0-4bec-86a5-7fe26f2ab8a5.png)

If you try to select and copy the text, it will have double `https://`: 
- `Patreon | https://https://t.co/VqkH2l6uLZ`

even without the userscript.

**Comment by cglmrfreeman** [comment]
Fantastic work as usual! Thanks much!
