### ISSUE TITLE
Firefox can no longer remember last saved location based on url

### ISSUE THREAD

**Issue by biggestsonicfan** [AlttiRi/twitter-click-and-save#32]
So a problem I've run into and thought it was a profile issue was Firefox's default ability to remember the last saved location based on a URL. This information is stored in the `content-prefs.sqlite` file. However, I am assuming how tcas saves file urls as blobs(?), this information is no longer utilized properly. For example, if I save a file in my twitter directory from tcas, then navigate to Pixiv and save an image there, it remembers that it should save it to my "pixiv" directory. If I go back to twitter and save an image with tcas, it wants to save it in the "pixiv" directory, as that was the last directory used. If I right click and try to save an image without tcas, it wants to save the file in the "twitter" directory.

This functionality seems to have only broken in the last month or so.

**Comment by AlttiRi** [comment]
For example,
```js
new URL(URL.createObjectURL(new Blob(["123"])))
```
on [github.com](https://github.com/) it creates a URL with
```js
{
  href: "blob:https://github.com/551fa0ce-5e8c-4000-a9a0-b533c0a60576",
  origin: "https://github.com"
}
```
on [twitter.com](https://twitter.com/)
```js
{
  href: "blob:https://twitter.com/233555b2-9429-4bbb-9d56-a37b07f9e792", 
  origin: "https://twitter.com/"
}
```

I use the standart way to download blob files:
```js
function downloadBlob(blob, name, url) {
    const anchor = document.createElement("a");
    anchor.setAttribute("download", name || "");
    const blobUrl = URL.createObjectURL(blob);
    anchor.href = blobUrl + (url ? ("#" + url) : "");
    anchor.click();
    setTimeout(() => URL.revokeObjectURL(blobUrl), 30000);
}
```

---

I did not know about this option in FF.

Try to run on different sites the follow code in the console:

```js
downloadBlob(new Blob([location.href], {type: "text/plain"}), `${location.hostname}.txt`);

function downloadBlob(blob, name, url) {
    const anchor = document.createElement("a");
    anchor.setAttribute("download", name || "");
    const blobUrl = URL.createObjectURL(blob);
    anchor.href = blobUrl + (url ? ("#" + url) : "");
    anchor.click();
    setTimeout(() => URL.revokeObjectURL(blobUrl), 3000);
}
```

If you think that it should save the file in a subfolder based on site's domain, report a bug on https://bugzilla.mozilla.org/.

**Comment by biggestsonicfan** [comment]
So I backed up my `content-prefs.sqlite` and found a tweet to save an image from and saved it twice, once with tcas and once by opening up the image and using right click and save as.

Here is the schema of the `content-prefs.sqlite` file:
![Screenshot_20230902_120820](https://github.com/AlttiRi/twitter-click-and-save/assets/9744201/6e169058-1926-45c1-b15e-7db64af41004)

The name of the right click -> save as file is simply `twitter.com`. The entry for the tcas is `blob:https://twitter.com/194b553f-b177-4e60-8721-d5b7c94a37fc#https://pbs.twimg.com/media/F5Cvng-bMAAroDt?format=jpg&name=small`, in which all right clicked and saved entries on twitter would save this `twitter.com` preference.

I suppose this is why my `content-prefs.sqlite` 15.7 megs containing 41,763 twitter blob entries.

As each blob is parsed as a unique entry, it's individual settings are initialized with the last download location, but since the specific blob probably won't be redownloaded again, the setting that is stored is not particularly useful.

The `browser.download.lastDir.savePerSite` is applied by default as `True` : https://udn.realityripple.com/docs/Mozilla/Preferences/Preference_reference/browser.download.lastDir.savePerSite

**Comment by biggestsonicfan** [comment]
Can confirm, `blob` protocol isn't handled [at this level](https://searchfox.org/mozilla-central/source/toolkit/mozapps/downloads/DownloadLastDir.sys.mjs#222):

```
  /**
   * Pre-processor to extract a domain name to be used with the content-prefs
   * service. This specially handles data and file URIs so that the download
   * dirs are recalled in a more consistent way:
   *  - all file:/// URIs share the same folder
   *  - data: URIs share a folder per mime-type. If a mime-type is not
   *    specified text/plain is assumed.
   * In any other case the original URL is returned as a string and ContentPrefs
   * will do its usual parsing.
   *
   * @param {string|nsIURI|URL} url The URL to parse
   * @returns {string} the domain name to use, or the original url.
   */
  #cpsGroupFromURL(url) {
    if (typeof url == "string") {
      url = new URL(url);
    } else if (url instanceof Ci.nsIURI) {
      url = URL.fromURI(url);
    }
    if (!URL.isInstance(url)) {
      return url;
    }
    if (url.protocol == "data:") {
      return url.href.match(/^data:[^;,]*/i)[0].replace(/:$/, ":text/plain");
    }
    if (url.protocol == "file:") {
      return "file:///";
    }
    return url.href;
  }
}
```
Which I find odd. I've never contributed to FF source before but will see what I can do.

**Comment by biggestsonicfan** [comment]
Bug/enhancement has been [filed](https://bugzilla.mozilla.org/show_bug.cgi?id=1851546).

**Comment by biggestsonicfan** [comment]
It's been [fixed](https://bugzilla.mozilla.org/show_bug.cgi?id=1822730) and set for release in v122. Closing.
