### ISSUE TITLE
About a problem found when using chrome

### ISSUE THREAD

**Issue by CHIHOLUEN** [AlttiRi/twitter-click-and-save#33]
I've noticed an issue with the plugin. The download button shows the video as 1080/1920, but the actual download is 720/1280. Any idea what might be causing this? Is there a way to fix it?

**Comment by AlttiRi** [comment]
It downloads the available mp4 file with higher bitrate.
https://github.com/AlttiRi/twitter-click-and-save/blob/bc4833aa8aec9a1d43e4fbebd88b3adb8c2bbc85/twitter-click-and-save.user.js#L1477-L1479
If there was a 1080p video version it would have the higher bitrate.


**How did you determine that the video (in a tweet) is FHD?**
**Could you give an example?**

---

I have uploaded a 1080p video, then Twitter resampled it to 720p.

There is no 1080p version in API response. Neither `.mp4`, nor `.m3u8`.

![Screenshot_1](https://github.com/AlttiRi/twitter-click-and-save/assets/16310547/7b732cd6-3899-4089-b9fb-ac10d45a783d)

![Screenshot_2](https://github.com/AlttiRi/twitter-click-and-save/assets/16310547/8f5742c9-0136-4e7e-a06f-27ede5934163)

**Comment by AlttiRi** [comment]
For example, a 1080p video: https://twitter.com/Koelet3D/status/1675946903727489024
Note: it's NSFW _(Cyberpunk 2077 R34)_, and it's big — 331 MB.

The userscript correctly downloads it.

**Comment by CHIHOLUEN** [comment]
> It downloads the available mp4 file with higher bitrate.
> 
> https://github.com/AlttiRi/twitter-click-and-save/blob/bc4833aa8aec9a1d43e4fbebd88b3adb8c2bbc85/twitter-click-and-save.user.js#L1477-L1479
> 
> 
> If there was a 1080p video version it would have the higher bitrate.
> **How did you determine that the video (in a tweet) is FHD?** **Could you give an example?**
> 
> I have uploaded a 1080p video, then Twitter resampled it to 720p.
> 
> There is no 1080p version in API response. Neither `.mp4`, nor `.m3u8`.
> 
> ![Screenshot_1](https://user-images.githubusercontent.com/16310547/268280121-7b732cd6-3899-4089-b9fb-ac10d45a783d.png)
> 
> ![Screenshot_2](https://user-images.githubusercontent.com/16310547/268278886-8f5742c9-0136-4e7e-a06f-27ede5934163.png)
> 
> UPD:
> 
> Although, yes, there are 1080p videos in Twitter. _...how to upload them?_
> 
> But even in this case of a real 1080p video:
> 
> > If there was a 1080p video version it would have the higher bitrate.
> 
> So, it would be downloaded.

> Thank you very much for getting back to my question. I can understand your response, so it seems like it's not a plugin issue indeed. I saw the videos as 1080P through the Twitter video downloader plugin, but the downloads are all in 720p. I initially thought it was a problem with the plugin, which is why I reported it. Sorry for any inconvenience caused. My apologies.

P.S. Your plugin is much more stable compared to Twitter video downloader. Thanks!
![20230915224715](https://github.com/AlttiRi/twitter-click-and-save/assets/128379439/9c8690b6-232c-4cd7-81e5-cd36a96bede5)
![20230915224654](https://github.com/AlttiRi/twitter-click-and-save/assets/128379439/b5d17dd0-08e4-46f9-934b-0351a270cee7)
