### ISSUE TITLE
QRT'd media is saved with the QRT author, not the original author

### ISSUE THREAD

**Issue by cglmrfreeman** [AlttiRi/twitter-click-and-save#4]
[Example](https://twitter.com/sew_angry/status/1545261660486701059).

The QRT was by sew_angry but the media was from volpinprops.

While I suppose the information saved in the filename could be used to trace the QRT, I would prefer the option of keeping the filename linked to the original tweet and not the QRT.

**Comment by AlttiRi** [comment]
Seems to be working.

Also I finally removed the annoying unclosable modal when browsing without an account:
![image](https://user-images.githubusercontent.com/16310547/183262529-23e79ea5-06ae-473f-912b-a03679e1cee9.png)
_(Need to enable the checkbox in the settings)_
Although, it will also remove the other popups, like email reviewing, I assume. Need to add the popup's text verifying, but it requires to check it for each language ("en", "es", "ru", "zh", "ja"). Okay, maybe sometime later.


And added support for bg downloading. (For example: https://twitter.com/SpaceX/header_photo)
_(Without keeping the history currently.)_

**Comment by cglmrfreeman** [comment]
Very satisfied, thanks again for such a wonderful script, use it every day!
