### ISSUE TITLE
[BUG] Some videos download thumbnail instead of video in media tab view

### ISSUE THREAD

**Issue by the-nelsonator** [AlttiRi/twitter-click-and-save#45]
Using Firefox 132.0b7 + Tampermonkey. Standard tracking protection setting, no change when turned totally off.

Steps to reproduce:

1. Open media tab in profile: https://x.com/Scooter_420/media
2. Attempt to download https://x.com/Scooter_420/status/1847004058391138620/ by clicking on download square on thumbnail.

Expected: downloads source mp4 (as it does when you click into the xeet's own page and download it from there): https://github.com/user-attachments/assets/d5de1292-49be-44bb-8ed9-1a834bfbec6e

Actual: downloads thumbnail jpg: 
https://github.com/user-attachments/assets/01b35e3e-ff6e-4ff8-8337-73340e12831b

Doesn't happen for all videos. For example, one that works from media tab view is https://x.com/shouldhaveanima/status/1847027305358467116 - this downloads mp4.

**Comment by AlttiRi** [comment]
https://github.com/AlttiRi/twitter-click-and-save/commit/672f57003216a912eec5e2c2c0bf52cd174bb38b
