### ISSUE TITLE
Date recorded in filename different from tweet post date

### ISSUE THREAD

**Issue by cglmrfreeman** [AlttiRi/twitter-click-and-save#5]
[Example](https://twitter.com/biggestsonicfan/status/1547828624467693568):
![Screenshot_20220808_224419](https://user-images.githubusercontent.com/9744201/183573470-86694d22-df1b-4764-96f1-86bf782b7820.png)
The tweeted video as I see it is dated `11:21 PM · Jul 14, 2022`, however the file that is saved by the script is dated `2022.07.15` in the filename.

Which is the "correct" date?

EDIT: Just read in the readme `The importans detail is it's UTC date.`

NEVERMIND!

**Comment by cglmrfreeman** [comment]
Reopening with a _different_ [example](https://twitter.com/casulcasulcasul/status/1547001717820370944):

According to _my_ twitter account timestamp, it says `4:35 PM · Jul 12, 2022`, which converted to a datetime object is `2022-07-12 16:35:26-07:53`.

Converting that to UTC, however, results in a timestamp of `2022-07-13 00:28:26+00:00`. However the script still wants to save it as `2022.07.12` :thinking:

**Comment by AlttiRi** [comment]
Set UTC in the Windows time settings and reload the page:
![image](https://user-images.githubusercontent.com/16310547/183595558-e288fb9b-1c70-4081-be17-8fdf40e489e3.png)

**Comment by cglmrfreeman** [comment]
Adjusting time to UTC (in linux) did not seem to affect the results. However, I will try to see if I can still calculate the _true_ UTC from the logs I have from [twMediaDownloader](https://github.com/furyutei/twMediaDownloader), which does not grab the last-modified.

**Comment by AlttiRi** [comment]
Probably it's the difference between time of adding the media to the tweet and the result tweet posting time.

gallery-dl also uses the same approach.
It sets to file's mtime the time from `last-modified` header. 
Also for formatting it uses UTC representation too (of `last-modified` time). 
It's the most correct way to store the time in the string (in the filename).
Any people from the whole world for the same media will have the same filename independently of time zones.

**Comment by cglmrfreeman** [comment]
> Probably it's the difference between time of adding the media to the tweet and the result tweet posting time.

That's bizarre. I never imagined that sort of thing would happen but it does make sense. Twitter does need to host it for you to see it as you post it.

I'm glad to know that gallery-dl keeps these timestamps too, so the time won't be different when saved with the recommended settings in the readme.

Alright, I think I'm fully satisfied here. Turned out to be a nonissue, lol.
