### ISSUE TITLE
Deleted tweet content saves as 0 byte .null file

### ISSUE THREAD

**Issue by cglmrfreeman** [AlttiRi/twitter-click-and-save#9]
If one were to casually save images through their feed, they might not notice the tweet was deleted and save the .null file without realizing that saving the image from the browsers cache (right click save as) will be their last chance to keep that image data.

Thankfully it appears I have only attempted to save one image in the past which is now lost, but I think a more intuitive way to let a user know the image is deleted, or perhaps pull the data from the browsers cache if a live link fails, would be more favorable than discovering you didn't save the data you intended and now it's gone.

Not sure how you'd test/sandbox this, but you would probably need two use two accounts.

EDIT: Perhaps after a fail give a type of message indicating the data could not be grabbed due to connection issues or deleted tweet?

**Comment by AlttiRi** [comment]
If an author have deleted a tweet, this tweet will not disappear in your timeline, since the tweet already is rendered by the site. Twitter does not notify your browser about this event.

The media of the deleted tweet are available for a notable time. So, if the tweet is deleted, but it is still presented in your browser you can successfully download the media.

Just checked it.

**Comment by AlttiRi** [comment]
I have never seen zero downloaded media on Twitter, but if it exists, it makes sense to do not add them in download history.

**Comment by cglmrfreeman** [comment]
The three null files I have:
`[twitter] S_ABOTEN__—2022.09.08—1567932683602526209—FcJqd1VaUAAoCig.null`
`[twitter] S_ABOTEN__—2022.09.08—1567932683602526209—FcJqdlhagAAXpf6.null`
`[twitter] Aoi_Tohka—1970.01.01—1566365668907565061—FbzZRU1aMAEyR2Z.null`

**Comment by AlttiRi** [comment]
Ok, I see. My the first image was tiny.

**Comment by cglmrfreeman** [comment]
Ah this did fix it though now! Thank you!

**Comment by AlttiRi** [comment]
[Make the button pink on a download error](https://github.com/AlttiRi/twitter-click-and-save/commit/934ee61c46e4ac9ce1d85391154e536b5e2d7ad3) https://github.com/AlttiRi/twitter-click-and-save/commit/934ee61c46e4ac9ce1d85391154e536b5e2d7ad3

**Comment by cglmrfreeman** [comment]
> [Make the button pink on a download error](https://github.com/AlttiRi/twitter-click-and-save/commit/934ee61c46e4ac9ce1d85391154e536b5e2d7ad3) [934ee61](https://github.com/AlttiRi/twitter-click-and-save/commit/934ee61c46e4ac9ce1d85391154e536b5e2d7ad3)

Oh snap that will be really useful!

**Comment by AlttiRi** [comment]
How it works:
Deleted images' URLs are available for a time after tweet deleting if someone has requested them before, but a new "resample" URL can't be created after tweet deleting.

If you see in the timeline an image with `?format=jpg&name=medium` and the tweet is not deleted you can download `?format=jpg&name=orig` — twitter will create the endpoint with the orig image.

You can use `?format=jpg&name=orig` after the tweet deleting only if someone already asked Tweeter to create this endpoint before the tweet was deleted.
